- lib/src/visibility_detector/src/visibility_detector_controller.dart
- pubspec.yaml
- test/visibility_detector/widget_test.dart
Fixes a breakage from Flutter v1.3 in the VisibilityDetector widget tests.
Note that the fix will require Flutter v1.1.3.
> Copybara sync

- CHANGELOG.md
- gallery/pubspec.yaml
- pubspec.yaml
No externally published widgets from flutter_widgets actually depend
on package:intl, so remove the dependency.  This avoids a version
mismatch between flutter's master branch and fluter's dev branch.
While I'm touching this, also adjust the format for the authors so
that pub stops complaining about it.
Fixes https://github.com/google/flutter.widgets/issues/25.
PiperOrigin-RevId: 268025975
> Remove flutter_widgets' dependency on package:intl

- packages/scrollable_positioned_list/CHANGELOG.md
- packages/scrollable_positioned_list/lib/src/positioned_list.dart
- packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart
- packages/scrollable_positioned_list/pubspec.yaml
- packages/scrollable_positioned_list/test/scrollable_positioned_list_test.dart
Ensure that itemBuilders not be called with indices > itemCount - 1.
fixes #42
fixes #77
Closes https://github.com/google/flutter.widgets/pull/89
Original author, and much thanks to, lkho <llhmtc@gmail.com>
PiperOrigin-RevId: 307163952
> [ScrollablePositionedList] Ensure that itemBuilders not be called with indices > itemCount - 1.

- .github/ISSUE_TEMPLATE/new-issue.md
Add an issue template, primarily to remind people people to specify what package their issue is about.
> Add an issue template

- packages/flutter_simple_treeview/CHANGELOG.md
- packages/flutter_simple_treeview/LICENSE
- packages/flutter_simple_treeview/README.md
- packages/flutter_simple_treeview/lib/flutter_simple_treeview.dart
- packages/flutter_simple_treeview/lib/src/builder.dart
- packages/flutter_simple_treeview/lib/src/node_widget.dart
- packages/flutter_simple_treeview/lib/src/tree_node.dart
- packages/flutter_simple_treeview/lib/src/tree_state.dart
- packages/flutter_simple_treeview/lib/src/tree_view.dart
- packages/flutter_simple_treeview/pubspec.yaml
- packages/flutter_simple_treeview/test/tree_state_test.dart
- packages/flutter_simple_treeview/test/tree_view_test.dart
PiperOrigin-RevId: 312307568
This is first part of renaming. I will delete flutter_tree with a separate PR, externally, without copybara.
NA
> Rename flutter_tree to flutter_simple_treeview - PR1

- analysis_options.yaml
- packages/visibility_detector/example/lib/main.dart
- tool/travis.sh
The `dartfmt` command has been replaced with `dart format`.
We currently can't quite replace `dartfmt` with `dart format` because the fix for https://github.com/dart-lang/sdk/issues/44582 hasn't reached the Flutter beta channel yet, so we can't rely on its exit code.  Additionally, unlike `dartfmt --dry-run`, `dart format
--output=none` prints status to stdout even if nothing's changed, so we can no longer rely on the output being empty either.
Luckily, `flutter format` does return a proper exit code, so use that.
Also, disable the `literal_only_boolean_expressions` lint. I don't see any value in it, and it's already banned internally.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and …
> Make tool/travis.sh use `flutter format` instead of `dartfmt`, disable a useless lint

- packages/visibility_detector/CHANGELOG.md
- packages/visibility_detector/example/lib/main.dart
- packages/visibility_detector/lib/src/visibility_detector_layer.dart
- packages/visibility_detector/pubspec.yaml
- packages/visibility_detector/test/widget_test.dart
This is a bug fix for an existing function. The VisibilityDetector did not work correctly with widgets that change the scale because it used an offset after the scaling was applied instead of before the scaling was applied. It seems to work fine with this change. I use it in my app now (but I have backported it and use it with Flutter 1.17 because Flutter 2.x does not work correctly in Firefox on Android yet).
https://github.com/google/flutter.widgets/issues/283
> Bug fix for using VisibilityDetector with FittedBox and Transform.scale.

- packages/visibility_detector/CHANGELOG.md
- packages/visibility_detector/lib/src/visibility_detector_layer.dart
- packages/visibility_detector/pubspec.yaml
https://github.com/flutter/flutter/pull/91753 will remove the unused `layerOffset` parameter from `Layer.addToScene` in Flutter. This change maintains forward-compatibility with that change.
n/a
> Remove unused layerOffset

- AUTHORS
- packages/scrollable_positioned_list/test/scrollable_positioned_list_test.dart
This is a pre-migration for flutter/flutter#98559. Changes are as the title.
- `findsNWidgets(2)` are changed to 1 since another one is used to be provided by the `FadeUpwardsPageTransitionsBuilder`, and now we're using more specific finders.
None, but it's suggested by @Hixie.
> [test] Use descendant finders with `FadeTransition`s

- packages/visibility_detector/lib/src/visibility_detector_layer.dart
Revert the changes of 674cf414019653b09decdbeef936ff181d68b7dd that had broken the build.
Resolves #354
> Fix null checks and assertions for visibility_detector (#354)

- AUTHORS
- packages/scrollable_positioned_list/example/test/scrollable_positioned_list_example_test.dart
- packages/scrollable_positioned_list/lib/src/positioned_list.dart
- packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart
- packages/scrollable_positioned_list/pubspec.yaml
- packages/scrollable_positioned_list/test/scrollable_positioned_list_test.dart
Compilations were failing due to Flutter SDK upgrade and a previous linting 'fix'.  Previous non-null `!` was restored
#361  - should be fixed with PR
> Fixes #361, where Flutter SDK upgrade impacted nullability requirements

- .github/workflows/build.yaml
- tool/validate.sh
- add support for github actions
I'm not sure what'll break here; I'll create this as a draft PR for now.
> add support for github actions

- packages/visibility_detector/lib/src/render_visibility_detector.dart
- packages/visibility_detector/test/render_visibility_detector_test.dart
- packages/visibility_detector/test/widget_test.dart
Uses new API added in Flutter to get the current transform and clip from the canvas. This allows using the Layer tree, which is generally smaller, when calculating transforms and clips for a render object.
I will test this on TAP before requesting review.
> Use the layer tree to do more efficient calculation of transform/clip

- packages/scrollable_positioned_list/CHANGELOG.md
- packages/scrollable_positioned_list/lib/src/positioned_list.dart
- packages/scrollable_positioned_list/pubspec.yaml
- packages/scrollable_positioned_list/test/positioned_list_test.dart
There're (obscure) cases where a `RegisteredElement` can point to a `RenderObject` that has never been laid out and querying the `RenderObject`'s size crashes the app. See the test for an example.
Maybe: internal b/183417182 
> Skip an `Element` if its `RenderObject` has never been laid out

- packages/visibility_detector/CHANGELOG.md
- packages/visibility_detector/example/lib/main.dart
- packages/visibility_detector/pubspec.yaml
visibility_detector: Fix analysis issues with Flutter 3.1.0
* Replace deprecated API usage.
* Fix the Flutter SDK version dependency to depend on Flutter 3.1.0.
Analysis previously failed with Flutter 3.0.5.
> visibility_detector: Fix analysis issues with Flutter 3.1.0

- packages/scrollable_positioned_list/CHANGELOG.md
- packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart
- packages/scrollable_positioned_list/pubspec.yaml
> dispose of the animation controller for ScrollablePositionedList when needed

- packages/visibility_detector/CHANGELOG.md
- packages/visibility_detector/lib/src/render_visibility_detector.dart
- packages/visibility_detector/pubspec.yaml
- packages/visibility_detector/test/render_visibility_detector_test.dart
Speculative fix for b/244342335
This would cause the kind of problem they're seeing in release mode. Hard to know if this definitively fixes that bug without a full reproduction, but it definitely fixes a potential bug in this library.
> Avoid accessing bounds of widget that has never been laid out

- packages/scrollable_positioned_list/lib/src/positioned_list.dart
Check for non-finite itemOffset, similar to what was done for reveal in #259.  
I'm not able to repo the exception myself, and the stacktrace I have is a bit vague, but I suspect itemOffset is not finite, causing an exception in round.  
b/242206216
- [ x] I signed the [CLA].
- [ x] All tests from running `flutter test` pass.
- [ x] `flutter analyze` does not report any problems on my PR. (analysis errors unrelated to this PR)
- [ x ] I am willing to follow-up on review comments in a timely manner.
> Check for non-finite item offset

- packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart
- packages/scrollable_positioned_list/test/horizontal_scrollable_positioned_list_test.dart
[scrollable_positioned_list] Fix default cache extents for horizontal lists.
Closes #439 #453
*TODO*
*TODO*
- [x ] I signed the [CLA].
- [x ] All tests from running `flutter test` pass.
- [x ] `flutter analyze` does not report any problems on my PR.
- [x ] I am willing to follow-up on review comments in a timely manner.
> [scrollable_positioned_list] Fix default cache extents for horizontal

- packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart
- packages/scrollable_positioned_list/test/scrollable_positioned_list_test.dart
Previously the GestureDetector caused the ScrollablePositionedList to loose a few pixels when scrolling started.
Part of work on #41.
*TODO*
*TODO*
> [scrollable_positioned_list] Fix manual scrolling accuracy.

- packages/visibility_detector/example/lib/main.dart
Fix the example for visibility_detector, on sdk>3.0.0 projects the word *extends* is not used anymore when implementing interfaces, it's replaced by *implements*.
See https://github.com/dart-lang/sdk/issues/51440#issuecomment-1434850500
`   info • 'renderView' is deprecated and shouldn't be used. Consider using RendererBinding.renderViews instead as the binding may manage multiple RenderViews. This feature was deprecated after
v3.10.0-12.0.pre • test/widget_test.dart:465:38 • deprecated_member_use`
> [visibility_detector] Fix example for dart 3.0.0
