.gitignore, CHANGELOG.md, CONTRIBUTING.md, LICENSE, analysis_options.yaml, gallery/lib/gallery.dart, gallery/lib/main.dart, gallery/lib/src/html_widget_page.dart, gallery/lib/src/tagged_text_page.dart, gallery/pubspec.yaml, gallery/test/widget_loading_test.dart, lib/flutter_widgets.dart, lib/src/html_widget/README.md, lib/src/html_widget/html_widget.dart, lib/src/tagged_text/README.md, lib/src/tagged_text/tagged_text.dart, pubspec.yaml, test/html_widget/html_widget_test.dart, test/tagged_text/tagged_text_test.dart
PiperOrigin-RevId: 213903300
Change-Id: I772ebe60361eb97c1ca44f6b2d578330f91fefcc
=> Project import generated by Copybara.

.travis.yml, gallery/lib/gallery.dart, gallery/lib/src/linked_scroll_controller_page.dart, gallery/test/widget_loading_test.dart, lib/src/linked_scroll_controller/README.md, lib/src/linked_scroll_controller/linked_scroll_controller.dart, test/linked_scroll_controller/linked_scroll_controller_test.dart, tool/travis.sh
Publishing the new LinkedScrollController.
Closes #4
=> Copybara sync

gallery/lib/gallery.dart
=> Fix an incorrect import in the Gallery app

CHANGELOG.md, lib/src/linked_scroll_controller/linked_scroll_controller.dart, pubspec.yaml, test/linked_scroll_controller/linked_scroll_controller_test.dart
=> Copybara sync version 0.1.10

CHANGELOG.md, lib/flutter_widgets.dart, lib/src/visibility_detector/demo.dart, lib/src/visibility_detector/src/visibility_detector_controller.dart, lib/src/visibility_detector/src/visibility_detector_layer.dart, pubspec.yaml, test/visibility_detector/demo_test.dart
=> Copybara sync for 0.1.11

packages/visibility_detector/CHANGELOG.md, packages/visibility_detector/README.md, packages/visibility_detector/example/lib/main.dart, packages/visibility_detector/example/pubspec.yaml, packages/visibility_detector/example/test/unit_test.dart, packages/visibility_detector/lib/demo.dart, packages/visibility_detector/pubspec.yaml, packages/visibility_detector/test/widget_test.dart
Update visibility_detector to 0.1.5-dev.
=> Copybara sync for visibility_detector 0.1.5-dev

tool/travis.sh
* If `dartfmt` encounters syntax errors, it prints an error message
to stderr and nothing to stdout.  We previously treated this as
passing `dartfmt`.  Use `set -e` at the beginning of the script to
treat it as a failure.
* `dartanalyzer` checks were broken:
* We pointed it to a non-existent `.analysis_options` file instead
of to `analysis_options.yaml`.
* For proper analysis, `dartanalyzer` requires a `pubspec.yaml`
file in the current directory or in the chain of parent
directories.  However, when we restructured the flutter.widgets
repository to store multiple packages, there is no longer a
single root `pubspec.yaml` file.  This breakage was undetected
because:
* We identified analysis failure by checking for a specific error
string ("[error]"), but that does not match actual output …
=> Improve Travis checks

packages/flutter_simple_treeview/CHANGELOG.md, packages/flutter_simple_treeview/README.md, packages/flutter_simple_treeview/example/lib/main.dart, packages/flutter_simple_treeview/example/pubspec.yaml, packages/flutter_simple_treeview/example/readme.md, packages/flutter_simple_treeview/pubspec.yaml
PiperOrigin-RevId: 313513829
Update links in flutter_simple_treeview.
na
=>  Update links in flutter_simple_treeview.

packages/self_storing_input/CHANGELOG.md, packages/self_storing_input/LICENSE, packages/self_storing_input/README.md, packages/self_storing_input/example/lib/main.dart, packages/self_storing_input/example/pubspec.yaml, packages/self_storing_input/example/readme.md, packages/self_storing_input/example/web/index.html, packages/self_storing_input/lib/self_storing_input.dart, packages/self_storing_input/lib/src/primitives/operation_result.dart, packages/self_storing_input/lib/src/primitives/saver.dart, packages/self_storing_input/lib/src/primitives/the_progress_indicator.dart, packages/self_storing_input/lib/src/self_storing_text.dart, packages/self_storing_input/lib/src/self_storing_text/edit_button.dart, packages/self_storing_input/lib/src/self_storing_text/overlay_box.dart, packages/self_storing_input/lib/src/self_storing_text/overlay_controller.dart, packages/self_storing_input/lib/src/self_storing_text/self_storing_text_style.dart, packages/self_storing_input/pubspec.yaml, packages/self_storing_input/test/self_storing_text_test.dart
This PR creates package 'self_storing_input' with first widget 'self_storing_text'.
N/A
=> Create new package self_storing_input.

packages/self_storing_input/CHANGELOG.md, packages/self_storing_input/lib/src/self_storing_text.dart, packages/self_storing_input/pubspec.yaml
Invoke setState on shared state change.
N/A
=> Fix bug in self_storing_input.

packages/flutter_simple_treeview/CHANGELOG.md, packages/flutter_simple_treeview/README.md, packages/flutter_simple_treeview/example/lib/main.dart, packages/flutter_simple_treeview/example/lib/trees/controller_usage.dart, packages/flutter_simple_treeview/example/lib/trees/tree_from_json.dart, packages/flutter_simple_treeview/example/readme.md, packages/flutter_simple_treeview/lib/src/node_widget.dart, packages/flutter_simple_treeview/pubspec.yaml
PiperOrigin-RevId: 337150992
*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them).*
*Replace this paragraph with a list of issues related to this PR. Indicate which of these issues are resolved or fixed by this PR.*
=>  Add example for json input for flutter_simple_treeview.

packages/flutter_simple_treeview/example/readme.md
PiperOrigin-RevId: 353420149
*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them).*
*Replace this paragraph with a list of issues related to this PR. Indicate which of these issues are resolved or fixed by this PR.*
=>  Make link secured to fix warning for flutter_simple_treeview.

AUTHORS, CONTRIBUTING.md, packages/scrollable_positioned_list/example/pubspec.yaml
Also make scrollable_positioned_list_example non-publishable. (The main motivation for that is to check Copybara's behavior when syncing to the internal repository.)
=> Adjust CONTRIBUTING.md to mention tests

packages/linked_scroll_controller/CHANGELOG.md, packages/linked_scroll_controller/pubspec.yaml
Removed null-safety version.
My package depends on it so I can't release a regular version.
*TODO*
*TODO*
=> Change version of LinkedScrollController.

packages/scrollable_positioned_list/lib/src/positioned_list.dart, packages/scrollable_positioned_list/lib/src/scroll_view.dart, packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart, packages/scrollable_positioned_list/lib/src/wrapping.dart, packages/scrollable_positioned_list/test/shrink_wrap_position_list_test.dart, packages/scrollable_positioned_list/test/shrink_wrap_scrollable_position_list_test.dart
support for shrinkWrap for scrollPositionList， fix the shrinkWrap make scroll error.
fix issue: #52
[ScrollablePositionedList: Provide shrinkWrap](https://github.com/google/flutter.widgets/issues/52)
=> feature: support for shrinkWrap

packages/flutter_simple_treeview/CHANGELOG.md, packages/flutter_simple_treeview/pubspec.yaml, packages/self_storing_input/CHANGELOG.md, packages/self_storing_input/pubspec.yaml
https://github.com/google/flutter.widgets/issues/301
=> Stable release for null safety for flutter_simple_treeview and self_storing_input.

.gitignore, packages/flutter_simple_treeview/example/lib/main.dart, packages/scrollable_positioned_list/example/test/scrollable_positioned_list_example_test.dart, packages/scrollable_positioned_list/lib/src/positioned_list.dart, packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart, packages/scrollable_positioned_list/test/horizontal_scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/reversed_scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/separated_scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/seperated_horizontal_scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/shrink_wrap_scrollable_position_list_test.dart, packages/self_storing_input/lib/src/self_storing_radio_group/shared_state.dart, packages/self_storing_input/lib/src/self_storing_text/self_storing_text_style.dart, packages/visibility_detector/lib/src/visibility_detector_layer.dart
Make sure the package's lints and tests all pass, so it can be added to flutter/tests. It's also missing newer Flutter related patterns for gitignore. 
=> Fix lints in the repo

packages/flutter_simple_treeview/pubspec.yaml
- populate the repository field of the pubspec
=> populate the repository field of the pubspec

packages/scrollable_positioned_list/CHANGELOG.md, packages/scrollable_positioned_list/pubspec.yaml
I should have bumped the version number when I merged #325. Bumping minor version since it's changing Flutter SDK version dependency (to one where more APIs have been updated to null safety). 
=> bump version from #325

packages/visibility_detector/CHANGELOG.md, packages/visibility_detector/pubspec.yaml
I should have bumped this version when doing #325 
=> bump visibility_detector version from #325

.github/workflows/build.yaml, tool/validate.sh
Fix the github actions CI:
- fix a version reference in the actions config file
- update the CI script to not fail the CI on info level analysis issues (we can revisit this in a future refactoring of the CI setup)
=> Fix the github actions CI

.github/workflows/build.yaml, README.md, packages/self_storing_input/pubspec.yaml, tool/readme.dart
Updates to the repo readme:
- add a github actions badge to the readme
- add a table describing the packages available in this repo to the readme
- add a script which can regenerate the readme table (to stdout); this is run manually
=> Updates to the repo readme

packages/flutter_simple_treeview/example/lib/main.dart, packages/flutter_simple_treeview/example/pubspec.yaml
Migrate the example of flutter_simple_treeview to null safety
=> Migrate simple_treeview example to null safety

packages/visibility_detector/test/render_visibility_detector_test.dart
- remove an unused import in `render_visibility_detector_test.dart`
- fix the CI
=> remove an unused import in render_visibility_detector_test.dart

packages/visibility_detector/README.md
- minor update to the readme to include a link to the pub.dev page
=> Update README.md for visibility_detector

packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart, packages/scrollable_positioned_list/test/scrollable_positioned_list_test.dart
[scrollable_positioned_list] Don't complete scrollTo future until scrolling done.
Closes #430
*TODO*
*TODO*
- [x ] I signed the [CLA].
- [x ] All tests from running `flutter test` pass.
- [x ] `flutter analyze` does not report any problems on my PR.
- [ x] I am willing to follow-up on review comments in a timely manner.
=> [scrollable_positioned_list] Don't complete scrollTo future until scrolling done.

packages/scrollable_positioned_list/pubspec.yaml
=> [scrollable_positioned_list] Update for push

packages/scrollable_positioned_list/test/scrollable_positioned_list_test.dart
=> Remove unintended line change

packages/scrollable_positioned_list/CHANGELOG.md, packages/scrollable_positioned_list/README.md, packages/scrollable_positioned_list/pubspec.yaml
- [x ] I signed the [CLA].
- [x ] All tests from running `flutter test` pass.
- [x ] `flutter analyze` does not report any problems on my PR.
- [x ] I am willing to follow-up on review comments in a timely manner.
=> Update docs and versions for publishing for ScrollOffsetListener

packages/scrollable_positioned_list/README.md, packages/scrollable_positioned_list/example/lib/main.dart, packages/scrollable_positioned_list/lib/src/scroll_offset_listener.dart, packages/scrollable_positioned_list/lib/src/scrollable_positioned_list.dart, packages/scrollable_positioned_list/test/scroll_offset_controller_test.dart
Add controller for making pixel based scrolls in the list.
Partially addresses #460 
#415
=> [scrollable_positioned_list] Scroll offset controller

packages/scrollable_positioned_list/CHANGELOG.md, packages/scrollable_positioned_list/lib/src/wrapping.dart, packages/scrollable_positioned_list/pubspec.yaml
Update for publishing ScollOffsetController 0.3.8
*TODO*
- [x ] I signed the [CLA].
- [x ] All tests from running `flutter test` pass.
- [x ] `flutter analyze` does not report any problems on my PR.
- [x ] I am willing to follow-up on review comments in a timely manner.
=> Update for publishing ScollOffsetController 0.3.8

.github/workflows/build.yaml, packages/scrollable_positioned_list/CHANGELOG.md, packages/scrollable_positioned_list/example/test/scrollable_positioned_list_example_test.dart, packages/scrollable_positioned_list/pubspec.yaml, packages/scrollable_positioned_list/test/horizontal_scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/positioned_list_test.dart, packages/scrollable_positioned_list/test/reversed_positioned_list_test.dart, packages/scrollable_positioned_list/test/reversed_scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/scroll_offset_controller_test.dart, packages/scrollable_positioned_list/test/scroll_offset_listener_test.dart, packages/scrollable_positioned_list/test/scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/separated_positioned_list_test.dart, packages/scrollable_positioned_list/test/separated_scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/seperated_horizontal_scrollable_positioned_list_test.dart, packages/scrollable_positioned_list/test/shrink_wrap_position_list_test.dart, packages/scrollable_positioned_list/test/shrink_wrap_scrollable_position_list_test.dart, packages/self_storing_input/CHANGELOG.md, packages/self_storing_input/example/lib/main.dart, packages/self_storing_input/example/pubspec.yaml, packages/self_storing_input/lib/src/self_storing_text/self_storing_text_style.dart, packages/self_storing_input/pubspec.yaml, packages/visibility_detector/CHANGELOG.md, packages/visibility_detector/example/pubspec.yaml, packages/visibility_detector/lib/src/render_visibility_detector.dart, packages/visibility_detector/pubspec.yaml
Prepare the visibility_detector  package for the removal of AbstractNode from the Flutter framework (https://github.com/flutter/flutter/pull/128973).
I had to make a ton of changes unrelated to the above because the stuff in this repo has bit rotted a fair bit and checks were failing otherwise. The changes outside of `packages/visibility_detector/lib/src/render_visibility_detector.dart` are totally unrelated to the above and just general house keeping to make the presubmit checks happy.
=> [visibility_detector] Adapt to upcoming changes in Flutter
